import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import { ApiError, apiFetch } from '@/lib/api/fetch';

/**
 * `apiFetch` is the only place this app calls `fetch`, and every screen depends
 * on it. It had no test at all.
 *
 * ── Where this came from ──
 *
 * Salvaged from `refactor/phase-7-frontend-foundations`, which was never merged:
 * the frontend it was written against was deleted and rebuilt from the reference
 * dashboard, so the implementation is different but the CONTRACT is the same.
 * Adapted case by case against what this `fetch.ts` actually does, and the cases
 * for behaviour it does NOT have were dropped rather than asserted. Those gaps
 * are listed at the bottom of this file, because a missing test is worth
 * recording where somebody will look for it.
 */

const BASE = 'http://localhost:5050/api';

/** A Response without hand-writing the same options every time. */
function jsonResponse(
    status: number,
    body: unknown,
    headers: Record<string, string> = {},
) {
    return new Response(body === undefined ? '' : JSON.stringify(body), {
        status,
        headers: { 'Content-Type': 'application/json', ...headers },
    });
}

/**
 * Queue one response per call, so a test asserting a retry can prove the SECOND
 * attempt is the one that succeeded rather than only that the promise resolved.
 */
function mockFetchSequence(...responses: Array<Response | Error>) {
    const fetchMock = vi.fn();
    for (const response of responses) {
        if (response instanceof Error) fetchMock.mockRejectedValueOnce(response);
        else fetchMock.mockResolvedValueOnce(response);
    }
    vi.stubGlobal('fetch', fetchMock);
    return fetchMock;
}

function lastInit(fetchMock: ReturnType<typeof vi.fn>): RequestInit {
    return fetchMock.mock.calls.at(-1)?.[1] as RequestInit;
}

/**
 * Drive a retry to completion without waiting for the real backoff.
 *
 * The backoff is jittered up to 2x, so the worst case for two retries is
 * 300 + 600 + 800 + 1600. Five seconds clears it.
 */
async function runWithTimers<T>(work: () => Promise<T>): Promise<T> {
    vi.useFakeTimers();
    try {
        const promise = work();
        await vi.advanceTimersByTimeAsync(5_000);
        return await promise;
    } finally {
        vi.useRealTimers();
    }
}

afterEach(() => {
    vi.unstubAllGlobals();
    vi.restoreAllMocks();
});

describe('the request it builds', () => {
    it('prefixes the backend base URL and the api segment', async () => {
        // The segment is the literal `api`, not `api/v1`. This app was copied
        // from a dashboard whose backend was versioned and every call 404'd
        // until the version came off.
        const fetchMock = mockFetchSequence(jsonResponse(200, { ok: true }));
        await apiFetch('/projects');

        expect(fetchMock.mock.calls[0][0]).toBe(`${BASE}/projects`);
    });

    it('sends the session cookie, or every request is anonymous', async () => {
        // better-auth authenticates by cookie. Without this the backend sees an
        // anonymous request and answers 401 to everything.
        const fetchMock = mockFetchSequence(jsonResponse(200, {}));
        await apiFetch('/users/me');

        expect(lastInit(fetchMock).credentials).toBe('include');
    });

    it('sets the JSON content type for an ordinary body', async () => {
        const fetchMock = mockFetchSequence(jsonResponse(201, { id: 'p1' }));
        await apiFetch('/projects', {
            method: 'POST',
            body: JSON.stringify({ name: 'Atlas' }),
        });

        expect(
            new Headers(lastInit(fetchMock).headers).get('Content-Type'),
        ).toBe('application/json');
    });

    it('leaves FormData alone, so the multipart boundary survives', async () => {
        // The defect this exists for. The boundary is generated by the browser
        // and only reaches the server if `fetch` sets the header itself;
        // forcing application/json made every upload arrive unparseable. This
        // product uploads avatars and project documents.
        const fetchMock = mockFetchSequence(jsonResponse(201, {}));
        const form = new FormData();
        form.append('file', new Blob(['x']), 'a.txt');

        await apiFetch('/profiles/me/avatar', { method: 'POST', body: form });

        expect(
            new Headers(lastInit(fetchMock).headers).has('Content-Type'),
        ).toBe(false);
    });

    it('keeps the content type when the caller also passes a header', async () => {
        // `...init` used to be spread AFTER the merged `headers`, so any caller
        // header replaced the whole object and took `Content-Type` with it. A
        // JSON POST then arrived with no content type and an unparseable body.
        // Latent, because nothing passed a header yet, which is exactly how it
        // would have been found the hard way.
        const fetchMock = mockFetchSequence(jsonResponse(200, {}));
        await apiFetch('/projects', {
            method: 'POST',
            body: JSON.stringify({ name: 'Atlas' }),
            headers: { 'X-Trace-Id': 'abc' },
        });

        const headers = new Headers(lastInit(fetchMock).headers);
        expect(headers.get('X-Trace-Id')).toBe('abc');
        expect(headers.get('Content-Type')).toBe('application/json');
    });

    it('still omits the content type for FormData with a caller header', async () => {
        const fetchMock = mockFetchSequence(jsonResponse(200, {}));
        const form = new FormData();
        form.append('file', new Blob(['x']), 'a.txt');

        await apiFetch('/documents', {
            method: 'POST',
            body: form,
            headers: { 'X-Trace-Id': 'abc' },
        });

        const headers = new Headers(lastInit(fetchMock).headers);
        expect(headers.get('X-Trace-Id')).toBe('abc');
        expect(headers.has('Content-Type')).toBe(false);
    });
});

describe('the value it returns', () => {
    it('returns the parsed body', async () => {
        mockFetchSequence(jsonResponse(200, { items: [1, 2], total: 2 }));

        await expect(apiFetch('/projects')).resolves.toEqual({
            items: [1, 2],
            total: 2,
        });
    });

    it('returns undefined for a 204, which is what a delete answers', async () => {
        mockFetchSequence(new Response(null, { status: 204 }));

        await expect(apiFetch('/projects/p1')).resolves.toBeUndefined();
    });

    it('returns undefined for a 200 with an empty body', async () => {
        // Some mutations reply 200 with nothing. Parsing that as JSON throws
        // "Unexpected end of JSON input", which is not a sentence for a user.
        mockFetchSequence(new Response('', { status: 200 }));

        await expect(apiFetch('/projects/p1/archive')).resolves.toBeUndefined();
    });
});

describe('how it fails', () => {
    it('throws an ApiError carrying the status call sites branch on', async () => {
        mockFetchSequence(
            jsonResponse(409, { message: 'That project is archived.' }),
        );

        await expect(apiFetch('/projects/p1')).rejects.toMatchObject({
            status: 409,
        });
    });

    it('prefers the API wording, which is written for a person', async () => {
        mockFetchSequence(
            jsonResponse(409, { message: 'That project is archived.' }),
        );

        await expect(apiFetch('/projects/p1')).rejects.toThrow(
            'That project is archived.',
        );
    });

    it('replaces an HTML error page with a sentence, never showing markup', async () => {
        // A proxy answering instead of the backend. The contract of
        // `ApiError.message` is that it is safe to toast verbatim.
        mockFetchSequence(
            new Response('<html><body>502 Bad Gateway</body></html>', {
                status: 502,
                headers: { 'Content-Type': 'text/html' },
            }),
        );

        const error = await apiFetch('/projects').catch((e: unknown) => e);
        expect(error).toBeInstanceOf(ApiError);
        expect((error as ApiError).message).not.toContain('<');
        expect((error as ApiError).message.length).toBeGreaterThan(0);
    });

    it('reports a transport failure as status 0, not as a server error', async () => {
        // `fetch` rejects only on a network-level failure: offline, DNS, CORS,
        // backend down. Status 0 is what lets a caller tell that apart from a
        // 500, and the browser's "Failed to fetch" never reaches a user.
        mockFetchSequence(new TypeError('Failed to fetch'));

        const error = await apiFetch('/projects').catch((e: unknown) => e);
        expect(error).toBeInstanceOf(ApiError);
        expect((error as ApiError).status).toBe(0);
        expect((error as ApiError).message).not.toContain('Failed to fetch');
    });

    it('turns a 2xx with a non-JSON body into a sentence', async () => {
        // Something between us and the backend answered 200 with an error page.
        // The SyntaxError's "Unexpected token '<'" must never reach a toast.
        mockFetchSequence(
            new Response('<html>hello</html>', {
                status: 200,
                headers: { 'Content-Type': 'text/html' },
            }),
        );

        const error = await apiFetch('/projects').catch((e: unknown) => e);
        expect(error).toBeInstanceOf(ApiError);
        expect((error as ApiError).message).not.toContain('Unexpected token');
    });
});

describe('retry', () => {
    it('retries a GET on 429 and returns the successful attempt body', async () => {
        // A dashboard page mounts many parallel queries. If a burst briefly
        // trips the per-IP throttle, a short retry lets it self-heal instead of
        // surfacing a 429.
        const fetchMock = mockFetchSequence(
            jsonResponse(429, { message: 'Too many requests' }),
            jsonResponse(200, { recovered: true }),
        );

        const result = await runWithTimers(() => apiFetch('/projects'));

        expect(result).toEqual({ recovered: true });
        expect(fetchMock).toHaveBeenCalledTimes(2);
    });

    it('retries a GET on 503', async () => {
        const fetchMock = mockFetchSequence(
            new Response('', { status: 503 }),
            jsonResponse(200, { ok: true }),
        );

        await runWithTimers(() => apiFetch('/projects'));

        expect(fetchMock).toHaveBeenCalledTimes(2);
    });

    it('gives up after two retries and throws the last status', async () => {
        const fetchMock = mockFetchSequence(
            jsonResponse(429, {}),
            jsonResponse(429, {}),
            jsonResponse(429, {}),
        );

        const error = await runWithTimers(() =>
            apiFetch('/projects').catch((e: unknown) => e),
        );

        // Three attempts total: the first plus two retries.
        expect(fetchMock).toHaveBeenCalledTimes(3);
        expect((error as ApiError).status).toBe(429);
    });

    it('NEVER retries a POST, because a 503 does not say whether it landed', async () => {
        // The rule that matters. Retrying a mutation that actually succeeded
        // creates a second record.
        const fetchMock = mockFetchSequence(jsonResponse(503, {}));

        const error = await apiFetch('/projects', {
            method: 'POST',
            body: '{}',
        }).catch((e: unknown) => e);

        expect(fetchMock).toHaveBeenCalledTimes(1);
        expect((error as ApiError).status).toBe(503);
    });

    it.each(['PATCH', 'PUT', 'DELETE'])('never retries a %s either', async (method) => {
        const fetchMock = mockFetchSequence(jsonResponse(429, {}));

        await apiFetch('/projects/p1', { method }).catch(() => undefined);

        expect(fetchMock).toHaveBeenCalledTimes(1);
    });

    it('does not retry a status that is not transient', async () => {
        // A 500 means the request itself failed, and repeating it just fails
        // again more slowly.
        const fetchMock = mockFetchSequence(jsonResponse(500, {}));

        await apiFetch('/projects').catch(() => undefined);

        expect(fetchMock).toHaveBeenCalledTimes(1);
    });

    it('treats a lowercase method as the same method', async () => {
        // The retry decision uppercases before comparing. Without that, `get`
        // would be read as a mutation and lose its retry.
        const fetchMock = mockFetchSequence(
            jsonResponse(429, {}),
            jsonResponse(200, { ok: true }),
        );

        await runWithTimers(() => apiFetch('/projects', { method: 'get' }));

        expect(fetchMock).toHaveBeenCalledTimes(2);
    });
});

/**
 * ── Cases deliberately NOT here, because this implementation has no such
 * behaviour ──
 *
 * The spec these were salvaged from covered four more things, and asserting them
 * would have been writing a test for code that does not exist:
 *
 *   - **A per-request timeout.** There is none: a hanging request hangs until
 *     the browser gives up. The earlier client abandoned it as a 408.
 *   - **`AbortSignal` handling.** A caller cannot cancel a request, and a
 *     cancelled query therefore cannot be told apart from a failure.
 *   - **`Retry-After`.** The backoff is fixed and jittered; a server saying how
 *     long to wait is ignored.
 *   - **`apiDownload`.** No such export. File downloads have no client yet.
 *
 * None of them is a regression, and none blocks a screen today. They are written
 * down because a gap nobody recorded is a gap nobody fixes.
 */
