/**
 * Shared client-side fetch helpers for dashboard API modules.
 *
 * Always sends the Better Auth session cookie (`credentials: 'include'`) and
 * throws `ApiError` for every failure. The CONTRACT of `ApiError.message` is
 * that it is human-readable and safe to put in a toast verbatim - raw
 * technical text ("Internal server error", "Failed to fetch",
 * "Unexpected token '<'", ThrottlerException, unbounded validation dumps)
 * must never leave this file. Callers that need to branch on specifics get
 * `status` and the raw backend `body`. The wording itself lives in
 * `lib/api/humane-error.ts`, shared with the server actions.
 */
import {
    ApiError,
    humaneMessage,
    NETWORK_MESSAGE,
    SERVER_MESSAGE,
} from './humane-error';

// The backend's global prefix is the literal `api` (pmt-backend/src/main.ts).
// NOT `api/v1`: this app was copied from a dashboard whose backend was
// versioned, and every call 404'd until the segment came off. better-auth is
// mounted separately at `/api/auth/*` and does not go through this client.
const BASE_URL = `${process.env.NEXT_PUBLIC_BACKEND_URL ?? 'http://localhost:5050'}/api`;

// Base backoff (ms) between retries, one entry per retry attempt. A dashboard
// page mounts many parallel queries at once; if a burst briefly trips the
// backend's per-IP throttle, a short retry lets it self-heal instead of
// surfacing a 429 to the user.
const RETRY_BACKOFF_MS = [300, 800];

// Full jitter on top of the base delay. Without it, N parallel GETs that all
// 429 together would retry in lockstep and re-collide on the same throttle
// window; jitter spreads them out. Client-side, so Math.random is fine here
// (unlike the `'use cache'` server fetch layer, which bans it).
const sleep = (base: number) =>
    new Promise<void>((resolve) =>
        setTimeout(resolve, base + Math.floor(Math.random() * base)),
    );

export async function apiFetch<T>(path: string, init?: RequestInit): Promise<T> {
  // A FormData body MUST NOT carry an explicit Content-Type. The boundary is
  // generated by the browser and only reaches the server if fetch sets the
  // header itself; forcing application/json here made every multipart upload
  // arrive as an unparseable body. This product uploads avatars and project
  // documents, so the case is real rather than theoretical.
  const isFormData =
    typeof FormData !== 'undefined' && init?.body instanceof FormData;

  const request = async (): Promise<Response> => {
    try {
      // `...init` FIRST, then the two things this client owns.
      //
      // It used to come last, which meant a caller passing `headers` replaced
      // the merged object wholesale and took `Content-Type` with it: a JSON POST
      // arrived with no content type and an unparseable body. Latent, because
      // nothing passed a header yet, which is exactly how it would have been
      // found the hard way. `credentials` is now equally non-negotiable, and
      // that is deliberate: a request from this client without the session
      // cookie is an anonymous request, which is never what a caller meant.
      return await fetch(`${BASE_URL}${path}`, {
        ...init,
        credentials: 'include',
        headers: {
          ...(isFormData ? {} : { 'Content-Type': 'application/json' }),
          ...init?.headers,
        },
      });
    } catch {
      // fetch() only rejects on network-level failure (offline, DNS, CORS,
      // backend down). The browser's TypeError text ("Failed to fetch" /
      // "Load failed") is not for users.
      throw new ApiError(NETWORK_MESSAGE, 0);
    }
  };

  let res = await request();
  // Retry only transient 429/503, and only for idempotent GETs (default) - a
  // retried POST/PATCH/DELETE could double-apply a mutation.
  const method = (init?.method ?? 'GET').toUpperCase();
  if (method === 'GET') {
    for (
      let attempt = 0;
      (res.status === 429 || res.status === 503) && attempt < RETRY_BACKOFF_MS.length;
      attempt++
    ) {
      await sleep(RETRY_BACKOFF_MS[attempt]);
      res = await request();
    }
  }

  if (!res.ok) {
    let body: unknown;
    try {
      body = await res.json();
    } catch {
      // Non-JSON error body (an HTML page from a proxy) - the status-based
      // mapping below covers it.
    }
    throw new ApiError(humaneMessage(res.status, body), res.status, body);
  }

  if (res.status === 204) return undefined as T;
  // Some mutations (e.g. DELETE) reply 200/201 with an empty body. Parsing that
  // as JSON throws "Unexpected end of JSON input", so read text first and only
  // parse when there is content.
  const text = await res.text();
  if (!text) return undefined as T;
  try {
    return JSON.parse(text) as T;
  } catch {
    // A 2xx with a non-JSON body means something between us and the backend
    // answered instead (proxy error page). The SyntaxError's "Unexpected
    // token '<'..." must never reach a toast.
    throw new ApiError(SERVER_MESSAGE, res.status);
  }
}

// Re-exported so callers can branch on `err instanceof ApiError` / `err.status`
// without importing a second module.
export { ApiError } from './humane-error';

// Re-exported from the shared neutral util so existing `@/lib/api/fetch` imports
// keep working.
export { buildQuery } from './query';
