// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    // What `prisma db seed` and `prisma migrate reset` run. Same entry point
    // as `pnpm seed`, so there is only one seed script to maintain.
    seed: 'ts-node --project tsconfig.json prisma/seed.ts',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
