// Static word lists the seeders draw from. Kept in one place so the data
// reads like a real agency's database instead of "Item 1, Item 2, Item 3".

export const FIRST_NAMES = [
  'Jabed',
  'Arif',
  'Rezina',
  'Sneha',
  'Tanvir',
  'Nusrat',
  'Rakib',
  'Mehedi',
  'Sadia',
  'Farhan',
  'Ayesha',
  'Imran',
  'Shakib',
  'Tasnim',
  'Rifat',
  'Sumaiya',
  'Naimul',
  'Jannat',
  'Sabbir',
  'Mahi',
  'Rasel',
  'Priya',
  'Asif',
  'Tuhin',
  'Nafisa',
  'Zahid',
  'Labib',
  'Ruma',
  'Sohel',
  'Anika',
  'Kamrul',
  'Ishrat',
  'Muntasir',
  'Bushra',
  'Rayhan',
  'Samira',
  'Tofael',
  'Nadia',
  'Emon',
  'Lamia',
  'Shohag',
  'Tania',
  'Fahim',
  'Mitu',
  'Rubel',
  'Sharmin',
  'Anis',
  'Rumana',
  'Jubayer',
  'Maliha',
  'Daniel',
  'Emma',
  'Lucas',
  'Olivia',
  'Noah',
  'Sophia',
  'Ethan',
  'Mia',
  'Liam',
  'Ava',
  'Marco',
  'Elena',
  'Viktor',
  'Ingrid',
  'Hiroshi',
  'Yuki',
  'Chen',
  'Mei',
  'Omar',
  'Layla',
  'Diego',
  'Camila',
  'Andre',
  'Nina',
  'Pavel',
  'Anna',
  'Kwame',
  'Zara',
  'Mateo',
  'Isabella',
];

export const LAST_NAMES = [
  'Hasan',
  'Rahman',
  'Islam',
  'Ahmed',
  'Chowdhury',
  'Karim',
  'Alam',
  'Hossain',
  'Akter',
  'Sultana',
  'Mahmud',
  'Siddique',
  'Bhuiyan',
  'Talukder',
  'Sarker',
  'Mia',
  'Khan',
  'Uddin',
  'Haque',
  'Jahan',
  'Nasrin',
  'Parvin',
  'Molla',
  'Sheikh',
  'Barua',
  'Das',
  'Roy',
  'Saha',
  'Ghosh',
  'Dutta',
  'Sen',
  'Bose',
  'Smith',
  'Johnson',
  'Williams',
  'Brown',
  'Garcia',
  'Miller',
  'Davis',
  'Rodriguez',
  'Martinez',
  'Anderson',
  'Taylor',
  'Thomas',
  'Moore',
  'Jackson',
  'Novak',
  'Kowalski',
  'Muller',
  'Schmidt',
  'Rossi',
  'Silva',
  'Nakamura',
];

export const COMPANY_PREFIXES = [
  'Northwind',
  'Brightpath',
  'Lumen',
  'Vertex',
  'Harborview',
  'Ironclad',
  'Silverline',
  'Bluepeak',
  'Redwood',
  'Stonebridge',
  'Cobalt',
  'Evergreen',
  'Summit',
  'Crestline',
  'Pinnacle',
  'Clearwater',
  'Trailhead',
  'Copperfield',
  'Nordic',
  'Atlas',
  'Meridian',
  'Zenith',
  'Beacon',
  'Compass',
  'Anchor',
  'Skyline',
  'Riverstone',
  'Goldleaf',
  'Amber',
  'Quartz',
  'Onyx',
  'Sable',
  'Lighthouse',
  'Foxglove',
  'Wildflower',
  'Maplewood',
  'Cedar',
  'Birchwood',
];

export const COMPANY_SUFFIXES = [
  'Digital',
  'Labs',
  'Studios',
  'Group',
  'Partners',
  'Media',
  'Ventures',
  'Collective',
  'Works',
  'Interactive',
  'Solutions',
  'Consulting',
  'Holdings',
  'Commerce',
  'Systems',
  'Brands',
  'Retail',
  'Health',
  'Legal',
  'Realty',
];

export const PROJECT_NOUNS = [
  'Storefront',
  'Booking Portal',
  'Marketing Site',
  'Brand Refresh',
  'Client Dashboard',
  'Landing Page Set',
  'Membership Area',
  'Knowledge Base',
  'Careers Site',
  'Donation Platform',
  'Event Microsite',
  'Course Portal',
  'Support Center',
  'Pricing Page',
  'Checkout Flow',
  'Onboarding Flow',
  'Design System',
  'Mobile App Site',
  'Investor Page',
  'Product Tour',
  'Blog Migration',
  'SEO Overhaul',
  'Speed Optimisation',
  'Analytics Rollout',
  'Directory Listing',
  'Booking Widget',
  'Menu Ordering',
  'Loyalty Program',
  'Newsletter Hub',
  'Case Study Library',
  'Partner Portal',
  'Intranet',
  'Property Search',
  'Job Board',
  'Ticketing Flow',
  'Quote Builder',
];

export const DESIGNATIONS = [
  'Junior Developer',
  'Mid Level Developer',
  'Senior Developer',
  'Lead Developer',
  'Frontend Developer',
  'Backend Developer',
  'Full Stack Developer',
  'WordPress Developer',
  'Webflow Developer',
  'Junior Designer',
  'Senior Designer',
  'UI Designer',
  'UX Designer',
  'Product Designer',
  'Brand Designer',
  'Motion Designer',
  'Project Manager',
  'Senior Project Manager',
  'Delivery Manager',
  'Operations Manager',
  'Head of Delivery',
  'Technical Lead',
  'SEO Specialist',
  'QA Engineer',
];

export const TIMEZONES = [
  'Asia/Dhaka',
  'Asia/Kolkata',
  'Asia/Dubai',
  'Europe/London',
  'Europe/Berlin',
  'Europe/Warsaw',
  'America/New_York',
  'America/Chicago',
  'America/Los_Angeles',
  'Australia/Sydney',
  'Asia/Singapore',
  'Asia/Tokyo',
];

export const BIOS = [
  'Focused on clean, accessible frontend work.',
  'Builds and maintains WordPress themes and plugins.',
  'Enjoys turning messy requirements into a clear plan.',
  'Works mostly on Webflow and Framer builds.',
  'Cares a lot about page speed and Core Web Vitals.',
  'Comes from a print background, now fully digital.',
  'Likes pairing on tricky layout problems.',
  'Handles most of the client facing calls on delivery.',
  'Spends the most time in Figma and design tokens.',
  'Keeps an eye on technical SEO across every build.',
  'Prefers small, well reviewed pull requests.',
  'Has shipped over forty client sites here.',
];

export const LEAVE_TYPE_CORE = [
  { name: 'Annual Leave', defaultDaysPerYear: 20 },
  { name: 'Sick Leave', defaultDaysPerYear: 14 },
  { name: 'Casual Leave', defaultDaysPerYear: 10 },
  { name: 'Maternity Leave', defaultDaysPerYear: 112 },
  { name: 'Paternity Leave', defaultDaysPerYear: 10 },
  { name: 'Bereavement Leave', defaultDaysPerYear: 5 },
  { name: 'Unpaid Leave', defaultDaysPerYear: 30 },
  { name: 'Study Leave', defaultDaysPerYear: 7 },
  { name: 'Marriage Leave', defaultDaysPerYear: 7 },
  { name: 'Compensatory Off', defaultDaysPerYear: 12 },
  { name: 'Hajj and Umrah Leave', defaultDaysPerYear: 30 },
  { name: 'Sabbatical', defaultDaysPerYear: 60 },
  { name: 'Work From Home', defaultDaysPerYear: 24 },
  { name: 'Half Day Leave', defaultDaysPerYear: 24 },
];

// Names used to build out the rest of the leave types, so the table clears
// 100 rows. Real companies have far fewer, but the extra rows make the leave
// filters and the summary report worth testing.
export const LEAVE_TYPE_EXTRA_PREFIXES = [
  'Special',
  'Emergency',
  'Religious',
  'Election',
  'Medical',
  'Family',
  'Training',
  'Conference',
  'Volunteer',
  'Relocation',
  'Quarantine',
  'Jury Duty',
  'Military',
  'Adoption',
  'Carer',
  'Blood Donation',
  'Examination',
  'Probation',
  'Notice Period',
  'Long Service',
];

export const LEAVE_REASONS = [
  'Family wedding out of town.',
  'Down with fever, will rest at home.',
  'Doctor appointment in the morning.',
  'Taking my parents for a medical checkup.',
  'Short trip already booked before joining.',
  'Need a day for personal paperwork.',
  'Moving to a new flat this week.',
  'Attending a training course.',
  'Eid holiday extension.',
  'Child is unwell.',
  'Recovering from a minor surgery.',
  'Sitting for a university exam.',
  null,
  null,
];

export const HOLIDAY_TEMPLATES = [
  { name: 'New Year Day', month: 0, day: 1, span: 1 },
  {
    name: 'Shaheed Day and International Mother Language Day',
    month: 1,
    day: 21,
    span: 1,
  },
  { name: 'Sheikh Mujib Birthday', month: 2, day: 17, span: 1 },
  { name: 'Independence Day', month: 2, day: 26, span: 1 },
  { name: 'Bengali New Year', month: 3, day: 14, span: 1 },
  { name: 'May Day', month: 4, day: 1, span: 1 },
  { name: 'Buddha Purnima', month: 4, day: 12, span: 1 },
  { name: 'Eid ul Fitr Holiday', month: 2, day: 30, span: 5 },
  { name: 'Eid ul Adha Holiday', month: 5, day: 6, span: 5 },
  { name: 'Ashura', month: 6, day: 5, span: 1 },
  { name: 'National Mourning Day', month: 7, day: 15, span: 1 },
  { name: 'Janmashtami', month: 7, day: 26, span: 1 },
  { name: 'Eid e Milad un Nabi', month: 8, day: 5, span: 1 },
  { name: 'Durga Puja Holiday', month: 9, day: 2, span: 3 },
  { name: 'Victory Day', month: 11, day: 16, span: 1 },
  { name: 'Christmas Day', month: 11, day: 25, span: 1 },
  { name: 'Company Foundation Day', month: 1, day: 8, span: 1 },
  { name: 'Company Retreat', month: 10, day: 14, span: 3 },
  { name: 'Year End Shutdown', month: 11, day: 29, span: 3 },
  { name: 'Quarter One Planning Day', month: 0, day: 15, span: 1 },
  { name: 'Quarter Two Planning Day', month: 3, day: 15, span: 1 },
  { name: 'Quarter Three Planning Day', month: 6, day: 15, span: 1 },
  { name: 'Quarter Four Planning Day', month: 9, day: 15, span: 1 },
  { name: 'Team Building Day', month: 5, day: 20, span: 1 },
  { name: 'Office Maintenance Shutdown', month: 4, day: 24, span: 2 },
  { name: 'Election Day', month: 0, day: 7, span: 1 },
  { name: 'Local Government Election', month: 8, day: 18, span: 1 },
  { name: 'Winter Break', month: 11, day: 20, span: 2 },
  { name: 'Summer Break', month: 6, day: 22, span: 2 },
  { name: 'Health Awareness Day', month: 3, day: 7, span: 1 },
  { name: 'Volunteering Day', month: 2, day: 5, span: 1 },
  { name: 'Founders Appreciation Day', month: 10, day: 3, span: 1 },
  { name: 'Client Appreciation Day', month: 1, day: 14, span: 1 },
  { name: 'Design Week Offsite', month: 8, day: 24, span: 2 },
  { name: 'Engineering Offsite', month: 5, day: 28, span: 2 },
];

export const BLOCKER_REASON_CORE = [
  'Unspecified', // protected fallback row, must exist
  'Waiting on client feedback',
  'Waiting on client assets',
  'Waiting on client credentials',
  'Missing or unclear requirements',
  'Third party API is down',
  'Third party API rate limit',
  'Hosting or server issue',
  'Domain or DNS issue',
  'SSL certificate issue',
  'Payment gateway approval pending',
  'Plugin conflict',
  'Theme update broke layout',
  'Database migration failed',
  'Staging environment unavailable',
  'Design not finalised',
  'Copy not delivered',
  'Translation not delivered',
  'Blocked by another task',
  'Blocked by another team',
  'Dependency version conflict',
  'Build pipeline failing',
  'Test environment out of sync',
  'Access permission missing',
  'Legal or compliance review pending',
  'Budget approval pending',
  'Scope change under discussion',
  'Key person on leave',
  'Hardware failure',
  'Internet outage at office',
  'Waiting on invoice clearance',
  'Unclear acceptance criteria',
];

export const BLOCKER_REASON_EXTRA_TOPICS = [
  'Cloudinary upload',
  'Slack webhook',
  'Redis queue',
  'Neon database',
  'Vercel deploy',
  'Cloudflare cache',
  'Stripe webhook',
  'PayPal sandbox',
  'Mailchimp sync',
  'HubSpot sync',
  'Google Analytics tag',
  'Search Console access',
  'Figma handoff',
  'Webflow CMS limit',
  'WordPress multisite',
  'Elementor template',
  'WooCommerce tax rule',
  'Shopify app',
  'Framer component',
  'Wix editor',
  'CDN purge',
  'Font licence',
  'Image licence',
  'Video encoding',
  'Accessibility audit',
  'Load testing',
  'Security scan',
  'Backup restore',
];

export const BLOCKER_DESCRIPTIONS = [
  'Client has not sent the logo files in vector format yet.',
  'The staging site returns a 502 after the last deploy.',
  'We cannot reach the payment sandbox from our IP range.',
  'Two plugins both register the same shortcode and break the page.',
  'The CMS collection hit its item limit, so new posts fail to save.',
  'Product copy for the pricing page is still missing.',
  'The client changed their mind on the hero layout mid build.',
  'Nobody has admin access to the DNS panel.',
  'The API we integrate with started returning 429 on every call.',
  'Fonts render differently on Safari and the client rejected it.',
  'Build fails on CI but passes locally, still digging.',
  'The migration script drops the custom fields table.',
  'Waiting for legal to approve the cookie banner wording.',
  'Client wants a new section that is not in the signed scope.',
  'The designer who owns this file is on leave until next week.',
];

export const BLOCKER_RESOLUTIONS = [
  'Client sent the files, imported and closed.',
  'Rolled back the deploy and patched the config.',
  'Whitelisted our office IP with the provider.',
  'Removed the older plugin and rewrote the shortcode.',
  'Upgraded the CMS plan, the limit is gone.',
  'Copy arrived from the client, page is live.',
  'Agreed on the original layout in a call.',
  'Got DNS access from the client IT team.',
  'Added caching and backoff, calls are stable now.',
  'Swapped to a web safe fallback and client approved.',
  'Pinned the Node version on CI, build is green.',
  'Fixed the migration and reran it on staging first.',
  'Legal approved the wording with two small edits.',
  'Logged it as an additional requirement instead.',
  'Another designer picked it up and finished it.',
];

export const PROJECT_DESCRIPTIONS = [
  'Full rebuild of the marketing site with a new content model.',
  'Migrate the existing blog and keep every URL redirecting properly.',
  'Design and build a booking flow that connects to their calendar.',
  'Refresh the brand across the site, decks, and social templates.',
  'Ecommerce build with local payment methods and tax rules.',
  'Speed and Core Web Vitals work on an existing WordPress site.',
  'New landing page set for a paid campaign launching next quarter.',
  'Members area behind login, with tiered access levels.',
  'Technical SEO audit followed by a phased fix rollout.',
  'Move a Wix site onto Webflow without losing search rankings.',
  'Build a design system in Figma and ship the matching components.',
  'Customer support knowledge base with search and article ratings.',
  'Careers site with an applicant form feeding their ATS.',
  'Donation platform with recurring giving and receipts.',
  'Multi language site with a shared component library.',
];

export const RUSH_REASONS = [
  'Client campaign goes live in two weeks and cannot move.',
  'Trade show deadline, the site must be up before the booth opens.',
  'Their current host shuts down at the end of the month.',
  'Investor demo scheduled, leadership asked for priority.',
  'Security issue on the old site, we need to replace it fast.',
  'Competitor launched, client wants to respond quickly.',
  'Contract bonus tied to an early delivery date.',
];

export const ON_HOLD_REASONS = [
  'Client paused the project pending internal budget approval.',
  'Waiting on the client to sign the revised scope.',
  'Client contact left the company, waiting for a replacement.',
  'Legal review of the data handling is taking longer than planned.',
  'Client asked to pause until after their busy season.',
];

export const CANCELLATION_REASONS = [
  'Client cancelled the engagement and settled the invoice.',
  'Budget was pulled during a company wide freeze.',
  'Client decided to keep the work in house.',
  'Merged into a larger project under a new agreement.',
  'Scope could not be agreed after three rounds.',
];

export const DOCUMENT_TITLES = {
  PRD: [
    'Product Requirements Document',
    'PRD v2 after discovery call',
    'Scope and Deliverables',
    'Technical Requirements',
  ],
  REQUIREMENT: [
    'Functional Requirements',
    'Content Requirements',
    'Integration Requirements',
    'Accessibility Requirements',
  ],
  MEETING_NOTE: [
    'Kickoff Call Notes',
    'Weekly Sync Notes',
    'Design Review Notes',
    'Handover Call Notes',
  ],
  CREDENTIAL: [
    'Staging Access',
    'CMS Admin Access',
    'Hosting Panel Access',
    'Analytics Access',
  ],
  ASSET: ['Brand Assets Pack', 'Product Photography', 'Logo Files', 'Icon Set'],
  DELIVERABLE: [
    'Homepage Design',
    'Final Style Guide',
    'Launch Checklist',
    'Handover Pack',
  ],
} as const;

export const DOCUMENT_DESCRIPTIONS = [
  'Shared by the client over email after the kickoff call.',
  'Latest version, replaces the one from last week.',
  'Includes the open questions we still need answered.',
  'Signed off by the client contact.',
  'Draft only, do not send to the client yet.',
  null,
  null,
];

export const CREDENTIAL_TEXTS = [
  'URL: https://staging.example.com\nUser: agency\nPassword: see password manager entry PV-1042',
  'CMS: https://cms.example.com/admin\nUser: pixelvega\nPassword: stored in 1Password, vault Clients',
  'Panel: cPanel on shared hosting\nUser: exmpl_adm\nNote: two factor is on, ask the client contact for the code',
  'Analytics property: GA4 G-XXXXXXX\nAccess granted to delivery@pixelvega.com',
];

export const FILE_SAMPLES = [
  { ext: 'pdf', mime: 'application/pdf', min: 120_000, max: 3_400_000 },
  {
    ext: 'docx',
    mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    min: 40_000,
    max: 900_000,
  },
  {
    ext: 'xlsx',
    mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    min: 30_000,
    max: 600_000,
  },
  {
    ext: 'pptx',
    mime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    min: 400_000,
    max: 8_000_000,
  },
  { ext: 'png', mime: 'image/png', min: 20_000, max: 2_200_000 },
  { ext: 'jpg', mime: 'image/jpeg', min: 40_000, max: 1_800_000 },
  { ext: 'zip', mime: 'application/zip', min: 200_000, max: 12_000_000 },
  { ext: 'csv', mime: 'text/csv', min: 2_000, max: 180_000 },
];

export const TIME_ENTRY_NOTES = [
  'Building the hero section.',
  'Fixing the mobile nav overflow.',
  'Hooking the contact form up to the CRM.',
  'Migrating the last batch of blog posts.',
  'Reviewing pull requests.',
  'Setting up redirects from the old URLs.',
  'Cleaning up the design tokens.',
  'Writing the launch checklist.',
  'Debugging the checkout tax rule.',
  'Optimising images and lazy loading.',
  'Pairing with the designer on spacing.',
  'Fixing accessibility issues from the audit.',
  null,
  null,
];

export const MEETING_NOTES = [
  'Daily standup.',
  'Sprint planning.',
  'Design critique session.',
  'Client call, not billed to a project.',
  'One to one with the manager.',
  'All hands meeting.',
  'Hiring interview panel.',
  'Retrospective.',
  'Internal training session.',
  'Process review with the delivery team.',
];

export const PLAN_TEXTS = [
  'Finish the hero and services sections today.',
  'Migrate the remaining twelve blog posts.',
  'Wire up the contact form and test the CRM handoff.',
  'Review the two open pull requests, then start on the footer.',
  'Set up the staging environment and share the link.',
  'Fix the three accessibility issues from yesterday.',
  'Build the pricing table component.',
  'Write the redirect map for the old URLs.',
  'Pair with the designer on the mobile breakpoints.',
  'Start the SEO metadata pass across all templates.',
];

export const ACCOMPLISHMENT_TEXTS = [
  'Hero and services sections are done and pushed to staging.',
  'Migrated all twelve posts, images still need alt text.',
  'Contact form works end to end, CRM receives the lead.',
  'Reviewed both pull requests and started the footer.',
  'Staging is live, link shared in the project channel.',
  'Fixed all three accessibility issues and reran the audit.',
  'Pricing table is built, waiting on final copy.',
  'Redirect map is written, needs a review before deploy.',
  'Mobile breakpoints sorted out with the designer.',
  'Metadata pass done on half the templates, rest tomorrow.',
];

export const REVIEW_COMMENTS = [
  'Good progress, keep the same pace.',
  'Please add a note on the blocker next time.',
  'Nice work getting staging up early.',
  'Let us discuss the redirect map before you deploy it.',
  'This matches the plan, thanks.',
  'Flagging that this project is behind on hours.',
];

export const INTERNAL_REVIEW_COMMENTS = [
  'Spacing on mobile is off between the cards, please fix.',
  'The form validation messages are missing.',
  'Fonts are not the ones in the style guide.',
  'Two links in the footer point to the wrong page.',
  'Lighthouse score dropped, images need compressing.',
  'Copy still has placeholder text in two sections.',
  'Looks good, matches the design and the requirements.',
  'Approved. Speed and accessibility both pass.',
];

export const CLIENT_FEEDBACK_COMMENTS = [
  'Please make the logo larger in the header.',
  'We would like a different photo in the hero.',
  'The blue is not our brand blue, can you check.',
  'Add a second call to action under the pricing table.',
  'Everything looks great, happy to sign this off.',
  'Approved, thank you for the quick turnaround.',
  'One small change and then we are done.',
  'The mobile menu is hard to tap on my phone.',
];

export const ADDITIONAL_REQUIREMENT_DESCRIPTIONS = [
  'Client asked over email to add a newsletter signup in the footer.',
  'Add a second language version of the homepage only.',
  'Client wants a live chat widget added before launch.',
  'Add a downloadable brochure with a gated form.',
  'They want the blog to support author profiles.',
  'Add a cookie consent banner that logs consent.',
  'Client asked for a testimonials slider on the homepage.',
  'Add a store locator map with filtering.',
  'They want the pricing page to support annual and monthly toggle.',
  'Add an events calendar with recurring events.',
  'Client asked for a custom 404 page with search.',
  'They want product comparison tables.',
  'Add a job listing section that pulls from a spreadsheet.',
  'Client wants a dark mode across the whole site.',
  'Add PDF invoice generation to the member area.',
];

export const SOURCE_CHANNELS = [
  'email',
  'upwork',
  'fiverr',
  'direct',
  'slack',
  'phone call',
  'client portal',
  'whatsapp',
];

export const AUDIT_ACTIONS = [
  'user.invited',
  'user.updated',
  'user.deleted',
  'user.password_changed',
  'user.password_reset',
  'profile.updated',
  'profile.avatar_updated',
];

export const NOTIFICATION_TITLES: Record<string, string> = {
  PROJECT_CREATED: 'A new project was created',
  MEMBER_ASSIGNED: 'You were assigned to a project',
  MEMBER_REMOVED: 'You were removed from a project',
  MEMBER_REASSIGNED: 'Your role on a project changed',
  MEMBER_HANDOVER: 'A project was handed over to you',
  PROJECT_STATUS_CHANGED: 'Project status changed',
  PROJECT_ON_HOLD: 'A project was put on hold',
  PROJECT_CANCELLED: 'A project was cancelled',
  PROJECT_PRIORITY_RAISED: 'Project priority was raised',
  DOCUMENT_UPLOADED: 'A new document was uploaded',
  BLOCKER_ASSIGNED: 'A blocker was assigned to you',
  WORK_REPORT_COMMENTED: 'Your work report got a comment',
  STANDUP_MISSED: 'You have not submitted today plan',
  WRAP_UP_MISSED: 'You have not submitted today wrap up',
  DEADLINE_APPROACHING: 'A project deadline is two days away',
  INTERNAL_REVIEW_SUBMITTED: 'A project is ready for internal review',
  INTERNAL_REVIEW_CHANGES_REQUIRED: 'Changes were requested on your work',
  PROJECT_READY_FOR_CLIENT: 'A project is ready for the client',
  CLIENT_FEEDBACK_APPROVED: 'The client approved the work',
  CLIENT_FEEDBACK_CHANGES_REQUESTED: 'The client requested changes',
  PROJECT_AUTO_COMPLETED: 'A project was completed',
  ADDITIONAL_REQUIREMENT_SUBMITTED: 'A new additional requirement was logged',
  ADDITIONAL_REQUIREMENT_FLAGGED_OUT_OF_SCOPE:
    'A requirement looks out of scope',
  ADDITIONAL_REQUIREMENT_APPROVED: 'An additional requirement was approved',
  ADDITIONAL_REQUIREMENT_REJECTED: 'An additional requirement was rejected',
  ADDITIONAL_REQUIREMENT_HOURS_OR_DEADLINE_CHANGED: 'Hours or deadline changed',
  LEAVE_REQUEST_SUBMITTED: 'A leave request needs your review',
  LEAVE_REQUEST_APPROVED: 'Your leave request was approved',
  LEAVE_REQUEST_REJECTED: 'Your leave request was rejected',
};

export const USER_AGENTS = [
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Safari/605.1.15',
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36',
  'Mozilla/5.0 (iPhone; CPU iPhone OS 18_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Mobile/15E148 Safari/604.1',
  'PostmanRuntime/7.54.0',
];
