import { IsIn, IsNotEmpty, IsString } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';
import { ProjectRole } from '@prisma/client';

const PROJECT_ROLES = Object.values(ProjectRole);

export class AddProjectMemberDto {
  // User.id is a string generated by better-auth, not guaranteed to be a
  // UUID, so @IsUUID() would reject every real user id.
  @ApiProperty({ example: 'FKlPeooYonpdtm6IW7eJkJJvA4sdr2Xg' })
  @IsString()
  @IsNotEmpty()
  userId!: string;

  @ApiProperty({ enum: PROJECT_ROLES, example: 'DEVELOPER' })
  @IsIn(PROJECT_ROLES)
  role!: ProjectRole;
}
