import {
  IsEnum,
  IsInt,
  IsNotEmpty,
  IsOptional,
  IsString,
  IsUUID,
  Min,
} from 'class-validator';
import { ApiPropertyOptional } from '@nestjs/swagger';
import { BlockerSeverity, BlockerStatus } from '@prisma/client';

// All fields are optional. A caller can edit description/severity, move the
// status forward, reassign ownership, or any combination at once.
// resolutionNotes/deadlineExtensionDays are only meaningful alongside
// status: RESOLVED. Rejected outright once the blocker is already RESOLVED,
// since it's locked and read only at that point.
export class UpdateBlockerDto {
  @ApiPropertyOptional({ example: 'DB schema not approved (escalated)' })
  @IsOptional()
  @IsString()
  @IsNotEmpty()
  description?: string;

  @ApiPropertyOptional({ enum: BlockerSeverity })
  @IsOptional()
  @IsEnum(BlockerSeverity)
  severity?: BlockerSeverity;

  @ApiPropertyOptional({ example: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890' })
  @IsOptional()
  @IsUUID()
  reasonId?: string;

  @ApiPropertyOptional({
    enum: BlockerStatus,
    description: 'Forward-only: OPEN -> IN_PROGRESS -> RESOLVED.',
  })
  @IsOptional()
  @IsEnum(BlockerStatus)
  status?: BlockerStatus;

  // User.id is a string generated by better-auth, not guaranteed to be a
  // UUID, so @IsUUID() would reject every real user id, same fix already
  // applied to AddProjectMemberDto.userId.
  @ApiPropertyOptional({
    example: 'FKlPeooYonpdtm6IW7eJkJJvA4sdr2Xg',
    description:
      'Who is now working the blocker. If omitted while moving status to IN_PROGRESS, the caller is auto-assigned. Must be an active member of the project.',
  })
  @IsOptional()
  @IsString()
  @IsNotEmpty()
  assignedToId?: string;

  @ApiPropertyOptional({
    example: 'PM approved schema, code updated',
    description: 'Required when status is RESOLVED.',
  })
  @IsOptional()
  @IsString()
  @IsNotEmpty()
  resolutionNotes?: string;

  @ApiPropertyOptional({
    example: 2,
    minimum: 1,
    description:
      "Days this blocker added to the project's deadline. Only valid when status is RESOLVED; added on top of the project's current deadline.",
  })
  @IsOptional()
  @IsInt()
  @Min(1)
  deadlineExtensionDays?: number;
}
