import {
  ArrayMinSize,
  IsArray,
  IsDateString,
  IsIn,
  IsNotEmpty,
  IsOptional,
  IsString,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { ProjectType } from '@prisma/client';

const PROJECT_TYPES = Object.values(ProjectType);

export class CreateProjectDto {
  @ApiProperty({ example: 'Acme Corp Website Redesign' })
  @IsString()
  name!: string;

  @ApiPropertyOptional({ example: 'Full redesign of the marketing site' })
  @IsOptional()
  @IsString()
  description?: string;

  // User.id is a string generated by better-auth, not guaranteed to be a
  // UUID, so @IsUUID() would reject every real user id.
  @ApiProperty({ example: 'FKlPeooYonpdtm6IW7eJkJJvA4sdr2Xg' })
  @IsString()
  @IsNotEmpty()
  clientId!: string;

  @ApiProperty({
    enum: PROJECT_TYPES,
    isArray: true,
    example: ['WORDPRESS', 'SEO'],
  })
  @IsArray()
  @ArrayMinSize(1)
  @IsIn(PROJECT_TYPES, { each: true })
  projectTypes!: ProjectType[];

  @ApiPropertyOptional({ example: '2026-08-01' })
  @IsOptional()
  @IsDateString()
  plannedStartDate?: string;

  @ApiPropertyOptional({ example: '2026-09-30' })
  @IsOptional()
  @IsDateString()
  deadline?: string;
}
