-- CreateEnum
CREATE TYPE "NotificationType" AS ENUM (
    'PROJECT_CREATED',
    'MEMBER_ASSIGNED',
    'MEMBER_REMOVED',
    'MEMBER_REASSIGNED',
    'MEMBER_HANDOVER',
    'PROJECT_STATUS_CHANGED',
    'PROJECT_ON_HOLD',
    'PROJECT_CANCELLED',
    'PROJECT_PRIORITY_RAISED',
    'DOCUMENT_UPLOADED',
    'BLOCKER_ASSIGNED',
    'WORK_REPORT_COMMENTED',
    'STANDUP_MISSED',
    'DEADLINE_APPROACHING',
    'INTERNAL_REVIEW_SUBMITTED',
    'INTERNAL_REVIEW_CHANGES_REQUIRED',
    'PROJECT_READY_FOR_CLIENT',
    'CLIENT_FEEDBACK_APPROVED',
    'CLIENT_FEEDBACK_CHANGES_REQUESTED',
    'PROJECT_AUTO_COMPLETED',
    'ADDITIONAL_REQUIREMENT_SUBMITTED',
    'ADDITIONAL_REQUIREMENT_FLAGGED_OUT_OF_SCOPE',
    'ADDITIONAL_REQUIREMENT_APPROVED',
    'ADDITIONAL_REQUIREMENT_REJECTED',
    'ADDITIONAL_REQUIREMENT_HOURS_OR_DEADLINE_CHANGED',
    'LEAVE_REQUEST_SUBMITTED',
    'LEAVE_REQUEST_APPROVED',
    'LEAVE_REQUEST_REJECTED'
);

-- CreateTable
CREATE TABLE "Notification" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" "NotificationType" NOT NULL,
    "title" TEXT NOT NULL,
    "message" TEXT,
    "metadata" JSONB,
    "readAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Notification_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Notification_userId_idx" ON "Notification"("userId");

-- CreateIndex
CREATE INDEX "Notification_userId_readAt_idx" ON "Notification"("userId", "readAt");

-- AddForeignKey
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
