import { Module } from '@nestjs/common';
import { AiModule } from '@/ai/ai.module';
import { TimeEntriesModule } from '@/projects/time-entries/time-entries.module';
import { ProjectAiSummaryController } from '@/ai/summary/project-ai-summary.controller';
import { ProjectAiSummaryService } from '@/ai/summary/project-ai-summary.service';
import { ProjectStatusReportsController } from '@/ai/status-reports/project-status-reports.controller';
import { ProjectStatusReportsService } from '@/ai/status-reports/project-status-reports.service';
import { ProjectReportsController } from '@/projects/reports/project/project-reports.controller';
import { ProjectReportService } from '@/projects/reports/project/project-report.service';

/**
 * Everything that reads ONE project and reports on it: the numeric project
 * report, the synchronous AI summary, and the saved AI status reports.
 *
 * The cross-developer report moved to `ReportsModule`, because it is not
 * scoped to a project.
 *
 * The AI features live here rather than in AiModule because they are reports
 * that happen to be generated by a model. Keeping them beside
 * ProjectReportService also means the status report reuses those numbers rather
 * than recalculating them, so the two can never disagree.
 *
 * TimeEntriesModule is imported for the project report's hour aggregation.
 */
@Module({
  imports: [AiModule, TimeEntriesModule],
  controllers: [
    ProjectReportsController,
    ProjectAiSummaryController,
    ProjectStatusReportsController,
  ],
  providers: [
    ProjectReportService,
    ProjectAiSummaryService,
    ProjectStatusReportsService,
  ],
  exports: [ProjectReportService],
})
export class ProjectReportsModule {}
