import { Module } from '@nestjs/common';
import { AiModule } from '@/ai/ai.module';
import { TimeTrackingModule } from '@/projects/time-entries/time-tracking.module';
import { ProjectAiSummaryController } from '@/ai/summary/project-ai-summary.controller';
import { ProjectAiSummaryService } from '@/ai/summary/project-ai-summary.service';
import { ProjectStatusReportsController } from '@/ai/status-report/project-status-reports.controller';
import { ProjectStatusReportsService } from '@/ai/status-report/project-status-reports.service';
import { ProjectReportsController } from '@/projects/reports/project/project-reports.controller';
import { ProjectReportService } from '@/projects/reports/project/project-report.service';
import { DeveloperReportsController } from '@/projects/reports/developer/developer-reports.controller';
import { DeveloperReportService } from '@/projects/reports/developer/developer-report.service';

/**
 * Everything that reads the project domain and reports on it: the numeric
 * project and developer reports, the synchronous AI summary, and the saved AI
 * status reports.
 *
 * The AI features live here rather than in AiModule because they are reports
 * that happen to be generated by a model. Keeping them beside
 * ProjectReportService also means the status report reuses those numbers rather
 * than recalculating them, so the two can never disagree.
 *
 * TimeTrackingModule is imported for the developer report's hour aggregation.
 */
@Module({
  imports: [AiModule, TimeTrackingModule],
  controllers: [
    ProjectReportsController,
    DeveloperReportsController,
    ProjectAiSummaryController,
    ProjectStatusReportsController,
  ],
  providers: [
    ProjectReportService,
    DeveloperReportService,
    ProjectAiSummaryService,
    ProjectStatusReportsService,
  ],
  exports: [ProjectReportService],
})
export class ReportingModule {}
